name: "Assignment Pull Request Creator"
description: "Scans for assignment folders and creates a pull request for each assignment."
author: "majikmate"

inputs:
  default-branch:
    description: "Default branch to create pull requests against"
    required: false
    default: "main"
  assignments-root-regex:
    description: "Regular expression to match assignment root folder paths"
    required: false
    default: "^assignments$"
  assignment-regex:
    description: "Regular expression to match assignment folders within the assignments folder"
    required: false
    default: '^assignment-\d+$'
  github-token:
    description: "GitHub token for API access"
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}

outputs:
  created-branches:
    description: "List of branches created"
    value: ${{ steps.create-assignments.outputs.created-branches }}
  created-pull-requests:
    description: "List of pull requests created"
    value: ${{ steps.create-assignments.outputs.created-pull-requests }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Create assignment pull requests
      id: create-assignments
      shell: bash
      env:
        DEFAULT_BRANCH: ${{ inputs.default-branch }}
        ASSIGNMENTS_ROOT_REGEX: ${{ inputs.assignments-root-regex }}
        ASSIGNMENT_REGEX: ${{ inputs.assignment-regex }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: python ${{ github.action_path }}/create_assignment_prs.py

branding:
  icon: "git-pull-request"
  color: "blue"
