name: "Assignment Pull Request Creator"
description: "Scans for assignment folders and creates a pull request for each assignment. Supports dry-run mode to simulate operations without making changes."
author: "majikmate"

inputs:
  default-branch:
    description: "Default branch to create pull requests against"
    required: false
    default: "main"
  assignments-root-regex:
    description: "Comma-separated list of regular expressions to match assignment root folder paths"
    required: false
    default: "^assignments$"
  assignment-regex:
    description: "Comma-separated list of regular expressions to match assignment paths and extract branch names using named groups. Use (?P<branch>...) to capture the branch name."
    required: false
    default: '^(?P<branch>assignment-\d+)$'
  github-token:
    description: "GitHub token for API access"
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}
  dry-run:
    description: "Simulate operations without actually creating branches or pull requests"
    required: false
    default: "false"

outputs:
  created-branches:
    description: "List of branches created"
    value: ${{ steps.create-assignments.outputs.created-branches }}
  created-pull-requests:
    description: "List of pull requests created"
    value: ${{ steps.create-assignments.outputs.created-pull-requests }}

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ github.action_path }}/go.mod

    - name: Build assignment-pr-creator
      shell: bash
      run: |
        cd ${{ github.action_path }}
        go build -o bin/assignment-pr-creator cmd/assignment-pr-creator/main.go

    - name: Create assignment pull requests
      id: create-assignments
      shell: bash
      env:
        DEFAULT_BRANCH: ${{ inputs.default-branch }}
        ASSIGNMENTS_ROOT_REGEX: ${{ inputs.assignments-root-regex }}
        ASSIGNMENT_REGEX: ${{ inputs.assignment-regex }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        DRY_RUN: ${{ inputs.dry-run }}
      run: ${{ github.action_path }}/bin/assignment-pr-creator

branding:
  icon: "git-pull-request"
  color: "blue"
