name: Assignment Pull Request Creator
description: Scans for assignment folders and creates a pull request for each assignment. Supports dry-run mode to simulate operations without making changes.
author: majikmate

inputs:
  default-branch:
    description: Default branch to create pull requests against
    required: false
    default: main
  assignment-regex:
    description: Comma-separated list of regular expressions to match assignment paths and extract branch names using capturing groups. Use (?P<name>...) for named groups or (...) for unnamed groups. Named groups take priority when both are present. Use \\, to escape literal commas within patterns.
    required: false
    default: ^assignments/(assignment-\d+)$
  github-token:
    description: GitHub token for API access
    required: true
  dry-run:
    description: Simulate operations without actually creating branches or pull requests
    required: false
    default: "yes"

outputs:
  created-branches:
    description: List of branches created
    value: ${{ steps.create-assignments.outputs.created-branches }}
  created-pull-requests:
    description: List of pull requests created
    value: ${{ steps.create-assignments.outputs.created-pull-requests }}

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: ${{ github.action_path }}/go.mod
        cache: true
        cache-dependency-path: ${{ github.action_path }}/go.sum

    - name: Build assignment-pr-creator
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        go build -o assignment-pr-creator ./cmd/assignment-pr-creator

    - name: Run assignment-pr-creator
      id: create-assignments
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        DEFAULT_BRANCH: ${{ inputs.default-branch }}
        ASSIGNMENT_REGEX: ${{ inputs.assignment-regex }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        DRY_RUN: ${{ inputs.dry-run }}
      run: |
        "${{ github.action_path }}/assignment-pr-creator"

branding:
  icon: git-pull-request
  color: blue
