name: "Assignment Pull Request Creator"
description: "Scans for assignment folders and creates a pull request for each assignment."
author: "majikmate"

inputs:
  assignments-folder:
    description: "Root folder containing assignments"
    required: false
    default: "assignments"
  assignment-regex:
    description: "Regular expression to match assignment folders"
    required: false
    default: '^assignment-\d+$'
  github-token:
    description: "GitHub token for API access"
    required: true
    default: ${{ github.token }}

outputs:
  created-branches:
    description: "List of branches created"
    value: ${{ steps.create-assignments.outputs.created-branches }}
  created-pull-requests:
    description: "List of pull requests created"
    value: ${{ steps.create-assignments.outputs.created-pull-requests }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests PyGithub

    - name: Create assignment pull requests
      id: create-assignments
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        ASSIGNMENTS_FOLDER: ${{ inputs.assignments-folder }}
        ASSIGNMENT_REGEX: ${{ inputs.assignment-regex }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
      run: python ${{ github.action_path }}/create_assignment_prs.py

branding:
  icon: "git-pull-request"
  color: "blue"
