# Conda environment for Assignment Pull Request Creator
name: assignment-pr-creator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - requests>=2.31.0
  - pip:
      - PyGithub>=1.59.0
      - types-requests # Type stubs for better type checking
