# Example workflow for using the Assignment Pull Request Creator
#
# This file shows how to use the action in your own repository.
# To use this example:
# 1. Copy this file to .github/workflows/ in your repository
# 2. Modify the parameters to match your assignment structure
# 3. Test with dry-run mode first (set dry-run: true)
# 4. Ensure your repository has assignments in the specified structure

name: Assignment Pull Request Example
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Enable dry-run mode (preview only)"
        type: boolean
        required: false
        default: true

jobs:
  create-assignment-prs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create assignment pull requests
        id: create-prs
        uses: majikmate/assignment-pull-request@main # or specific version tag
        with:
          assignments-root-regex: "^assignments$"
          assignment-regex: '^assignment-\d+$'
          default-branch: "main"
          dry-run: ${{ inputs.dry-run || true }} # Default to dry-run for safety
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display results
        run: |
          echo "Created branches: ${{ steps.create-prs.outputs.created-branches }}"
          echo "Created pull requests: ${{ steps.create-prs.outputs.created-pull-requests }}"
